return {
    { "nvim-lualine/lualine.nvim",
        config = require("user.plugins.lualine"),
    },
    { "EdenEast/nightfox.nvim",
        config = require("user.plugins.nightfox"),
    },
    { "ellisonleao/gruvbox.nvim" ,
        config = require("user.plugins.gruvbox"),
    },
    { "ethanholz/nvim-lastplace" ,
        config = require("user.plugins.nvim-lastplace"),
    },
    { "catppuccin/nvim", as = "catppuccin" ,
        config = require("user.plugins.catppuccin"),
    },
    { "sainnhe/sonokai" ,
        config = require("user.plugins.sainnhe"),
    },
}
